### ISSUE TITLE
Prettier included as "dep" instead of "devDep"

### ISSUE THREAD

**Issue by ksnyde** [googleapis/nodejs-proto-files#24]
https://github.com/googleapis/nodejs-proto-files/blob/master/package.json#L57

I am writing lambda functions and was shocked at how HUGE the prettier package is. Clearly this is just meant for development purposes but you it listed as a dependency which then gets included as a upstream of anyone using `firebase-admin`. This is a contributor in pushing a <1mb function to 37mb. 

Here's a screenshot of a Lambda function which illustrates the overall impact of just this one mistake:

![image](https://user-images.githubusercontent.com/980757/36238539-1eb0ba86-11b8-11e8-8608-19d418a03bf9.png)

Most of the dead code -- to be honest -- comes from Firestore and some Storage API deps but I have less insight to the others. This one seems like a no-brainer.

**Comment by stephenplusplus** [comment]
Woops. Thanks for pointing this out. PR: #25
