### ISSUE TITLE
Include TypeScript types

### ISSUE THREAD

**Issue by bramkragten** [googleapis/nodejs-proto-files#343]
It would be nice if this package would include TypeScript types.

We now use `proto-loader-gen-types` (<https://github.com/grpc/grpc-node/tree/master/packages/proto-loader#generating-typescript-types>) to create types, but it would of course be easier if this package would just include them.

**Comment by alexander-fenster** [comment]
Hi @bramkragten,

We can technically provide `.d.ts` generated by protobufjs, this does not seem like something too complicated; but before doing that, can you please share your use case with this package? I would like to learn why folks are choosing to use nodejs-proto-files and not the `@google-cloud/*` client libraries (that are in TypeScript and have proto files included).

**Comment by bramkragten** [comment]
We use it for HomeGraph, I don't think there is a `@google-cloud` package for HomeGraph?

There is `@googleapis/homegraph`, but that only supports HTTP calls? And the performance was just not enough for us, so we use GRPC now.

**Comment by bcoe** [comment]
@bramkragten since this issue was opened, @googleapis/homegraph should now support http2:
